version: '3.7'

services:
  web:
    build: ./services/web
    command: gunicorn --bind 0.0.0.0:5000 wsgi:app
    volumes:
      - ./services/web/:/usr/src/app/
    ports:
      - 5000
    env_file:
      - ./.env
    depends_on:
      - "db"
  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - 5434:5432
    env_file:
      - ./.env
  nginx:
    build: ./services/nginx
    ports:
      - 8080:80
    depends_on:
      - web

volumes:
  postgres_data: